/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import Modelo.Cliente;
import Modelo.ClienteDAO;
//import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
//import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rosal
 */
public class Cliente2 extends javax.swing.JFrame 
{

    /**
     * Creates new form Cliente2
     */
    Cliente cli = new Cliente();
    ClienteDAO clidao = new ClienteDAO();
    DefaultTableModel modelo = new DefaultTableModel();
    public Cliente2() 
    {
        initComponents();
    }
    
    public void MostrarCliente()
    {
        List<Cliente> MostrarCli = clidao.MostrarCliente();
        modelo = (DefaultTableModel) tbCLIENTE.getModel();
        Object[] ob = new Object[4];
        
        for (int i = 0; i<MostrarCli.size(); i++) 
        {
            ob[0] = MostrarCli.get(i).getID_CLIENTE();
            ob[1] = MostrarCli.get(i).getNOMBRE_CLIENTE();
            ob[2] = MostrarCli.get(i).getTELEFONO_CLIENTE();
            ob[3] = MostrarCli.get(i).getCORREO_CLIENTE();
            modelo.addRow(ob);
        }
        tbCLIENTE.setModel(modelo);
    }
    
    public void LimpiarTable()
    {
        for(int i=0; i<modelo.getRowCount();i++)
        {
            modelo.removeRow(i);
            i = i-1;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCNOMBRE = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCTELEFONO = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCCORREO = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCLIENTE = new javax.swing.JTable();
        btnCMOSTRAR = new javax.swing.JButton();
        btnCMODIFICAR = new javax.swing.JButton();
        btnCELIMINAR = new javax.swing.JButton();
        btnCBUSCAR = new javax.swing.JButton();
        btnCAGREGAR = new javax.swing.JButton();
        btnCLIMPIAR1 = new javax.swing.JButton();
        btnCACTUALIZAR1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 70, -1));
        jPanel1.add(txtCID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 230, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Clientes");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, -1, -1));
        jPanel1.add(txtCNOMBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 230, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NOMBRE");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 80, -1));
        jPanel1.add(txtCTELEFONO, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 230, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("TELEFONO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 110, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CORREO");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 80, -1, -1));
        jPanel1.add(txtCCORREO, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, 230, -1));

        tbCLIENTE.setBackground(new java.awt.Color(51, 51, 51));
        tbCLIENTE.setForeground(new java.awt.Color(255, 255, 255));
        tbCLIENTE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "TELEFONO", "CORREO"
            }
        ));
        jScrollPane1.setViewportView(tbCLIENTE);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 980, 310));

        btnCMOSTRAR.setText("Mostrar");
        btnCMOSTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCMOSTRARActionPerformed(evt);
            }
        });
        jPanel1.add(btnCMOSTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, -1));

        btnCMODIFICAR.setText("Modificar");
        btnCMODIFICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCMODIFICARActionPerformed(evt);
            }
        });
        jPanel1.add(btnCMODIFICAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, -1, -1));

        btnCELIMINAR.setText("Eliminar");
        btnCELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCELIMINARActionPerformed(evt);
            }
        });
        jPanel1.add(btnCELIMINAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 500, -1, -1));

        btnCBUSCAR.setText("Buscar");
        btnCBUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCBUSCARActionPerformed(evt);
            }
        });
        jPanel1.add(btnCBUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 500, -1, -1));

        btnCAGREGAR.setText("Agregar");
        btnCAGREGAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCAGREGARActionPerformed(evt);
            }
        });
        jPanel1.add(btnCAGREGAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, -1, -1));

        btnCLIMPIAR1.setText("Limpiar");
        btnCLIMPIAR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCLIMPIAR1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnCLIMPIAR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 500, -1, -1));

        btnCACTUALIZAR1.setText("Actualizar");
        btnCACTUALIZAR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCACTUALIZAR1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnCACTUALIZAR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 500, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCMOSTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCMOSTRARActionPerformed
    MostrarCliente();   
    // TODO add your handling code here:
    }//GEN-LAST:event_btnCMOSTRARActionPerformed

    private void btnCBUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCBUSCARActionPerformed
        String idCliente = txtCID.getText();
        String nombreCliente = txtCNOMBRE.getText();
        String telefonoCliente = txtCTELEFONO.getText();
        String correoCliente = txtCCORREO.getText();
        
        List<Cliente> busquedaCli = clidao.BuscarCliente(idCliente, nombreCliente, telefonoCliente, correoCliente);
        
        LimpiarTable();
        
        for(Cliente cli : busquedaCli)
        {
            Object[] fila = {cli.getID_CLIENTE(), cli.getNOMBRE_CLIENTE(), cli.getTELEFONO_CLIENTE(), cli.getCORREO_CLIENTE()};
            modelo.addRow(fila);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCBUSCARActionPerformed

    private void btnCAGREGARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCAGREGARActionPerformed
    if(!"".equals(txtCID.getText())|| !"".equals(txtCNOMBRE.getText()) || !"".equals(txtCTELEFONO.getText()) ||!"".equals(txtCCORREO.getText()))
    {
        Cliente cliente = new Cliente();
        
        cliente.setID_CLIENTE(txtCID.getText());
        cliente.setNOMBRE_CLIENTE(txtCNOMBRE.getText());
        cliente.setTELEFONO_CLIENTE(txtCTELEFONO.getText());
        cliente.setCORREO_CLIENTE(txtCCORREO.getText());
        
        ClienteDAO clienteDAO = new ClienteDAO();
        clienteDAO.AgregarCliente(cliente);
        
        JOptionPane.showMessageDialog(null, "Cliente Registrado");
    }
    else
    {
        JOptionPane.showMessageDialog(null, "Campos Vacios");
    }
    
            // TODO add your handling code here:
    }//GEN-LAST:event_btnCAGREGARActionPerformed

    private void btnCELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCELIMINARActionPerformed
    if(!"".equals(txtCID.getText()))
    {
        int pregunta = JOptionPane.showConfirmDialog(null, "¡Desea Eliminar?");
        if (pregunta == 0)
        {
            String ID_CLIENTE = (txtCID.getText());
            clidao.EliminarCliente(ID_CLIENTE); //720 Ltable, prod lostprot
        }
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCELIMINARActionPerformed

    private void btnCLIMPIAR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCLIMPIAR1ActionPerformed
        LimpiarTable();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCLIMPIAR1ActionPerformed

    private void btnCMODIFICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCMODIFICARActionPerformed
    if("".equals(txtCID.getText()))
    {
        JOptionPane.showMessageDialog(null, "Seleccione una Fila");
    }
    else
    {
        if(!"".equals(txtCID.getText()) ||"".equals(txtCNOMBRE.getText()) ||"".equals(txtCTELEFONO.getText()) ||"".equals(txtCCORREO.getText()))
        {
            cli.setID_CLIENTE(txtCID.getText());
            cli.setNOMBRE_CLIENTE(txtCNOMBRE.getText());
            cli.setTELEFONO_CLIENTE(txtCTELEFONO.getText());
            cli.setCORREO_CLIENTE(txtCCORREO.getText());
            
            clidao.ModificarCliente(cli);
            JOptionPane.showMessageDialog(null, "Cliente Modificado");
            
        }
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCMODIFICARActionPerformed

    private void btnCACTUALIZAR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCACTUALIZAR1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCACTUALIZAR1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCACTUALIZAR1;
    private javax.swing.JButton btnCAGREGAR;
    private javax.swing.JButton btnCBUSCAR;
    private javax.swing.JButton btnCELIMINAR;
    private javax.swing.JButton btnCLIMPIAR1;
    private javax.swing.JButton btnCMODIFICAR;
    private javax.swing.JButton btnCMOSTRAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbCLIENTE;
    private javax.swing.JTextField txtCCORREO;
    private javax.swing.JTextField txtCID;
    private javax.swing.JTextField txtCNOMBRE;
    private javax.swing.JTextField txtCTELEFONO;
    // End of variables declaration//GEN-END:variables
}
