/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import Modelo.Direccion;
import Modelo.DireccionDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rosal
 */
public class Direccion2 extends javax.swing.JFrame {

    /**
     * Creates new form Direccion2
     */
    Direccion dir = new Direccion();
    DireccionDAO dirdao = new DireccionDAO();
    DefaultTableModel modelo = new DefaultTableModel();
    
    public Direccion2() 
    {
        initComponents();
    }
    
    public void MostrarDireccion()
    {
        List<Direccion> MostrarDir = dirdao.MostrarDireccion();
        modelo = (DefaultTableModel) tbDireccion.getModel();
        Object[] ob = new Object[7];
        
        for (int i = 0; i < MostrarDir.size(); i++) 
        {
            ob[0] = MostrarDir.get(i).getID_DIRECCION();
            ob[1] = MostrarDir.get(i).getALCALDIA_MUNICIPIO();
            ob[2] = MostrarDir.get(i).getCP();
            ob[3] = MostrarDir.get(i).getCALLE();
            ob[4] = MostrarDir.get(i).getNUM_EXT();
            ob[5] = MostrarDir.get(i).getCOLONIA();
            ob[6] = MostrarDir.get(i).getID_ESTADO();
            modelo.addRow(ob);
        }
        tbDireccion.setModel(modelo);
    }
    
    public void LimpiarTable()
    {
        for(int i=0; i<modelo.getRowCount();i++)
        {
            modelo.removeRow(i);
            i = i-1;
        }
    }

    /**
     * This method is called from wit7hin the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtD_ID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtD_ALCALDIA = new javax.swing.JTextField();
        txtD_CP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtD_CALLE = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtD_NUM_EXT = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtD_COLONIA = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtD_ID_ESTADO = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDireccion = new javax.swing.JTable();
        btnD_BUSCAR = new javax.swing.JButton();
        btnD_MOSTRAR = new javax.swing.JButton();
        btnD_AGREGAR = new javax.swing.JButton();
        btnD_MODIFICAR = new javax.swing.JButton();
        btnD_ELIMINAR = new javax.swing.JButton();
        btnD_LIMPIAR = new javax.swing.JButton();
        btnD_ACTUALIZAR1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Direccion");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));

        txtD_ID.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txtD_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 130, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 130, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ALCALDIA/MUNICIPIO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 130, -1));

        txtD_ALCALDIA.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txtD_ALCALDIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 130, -1));

        txtD_CP.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txtD_CP, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 130, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CP");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 130, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CALLE");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 130, -1));

        txtD_CALLE.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txtD_CALLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 130, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("NUMERO EXTERIOR");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 130, -1));

        txtD_NUM_EXT.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txtD_NUM_EXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 130, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("COLONIA");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 110, 130, -1));

        txtD_COLONIA.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txtD_COLONIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 140, 130, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("ID ESTADO");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 110, 130, -1));

        txtD_ID_ESTADO.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txtD_ID_ESTADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 140, 130, -1));

        tbDireccion.setBackground(new java.awt.Color(51, 51, 51));
        tbDireccion.setForeground(new java.awt.Color(255, 255, 255));
        tbDireccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ALCALDIA/MUNICIPIO", "CP", "CALLE", "NUM_EXT", "COLONIA", "ID_ESTADO"
            }
        ));
        jScrollPane1.setViewportView(tbDireccion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 1040, 280));

        btnD_BUSCAR.setBackground(new java.awt.Color(153, 153, 153));
        btnD_BUSCAR.setForeground(new java.awt.Color(51, 51, 51));
        btnD_BUSCAR.setText("Buscar");
        btnD_BUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD_BUSCARActionPerformed(evt);
            }
        });
        jPanel1.add(btnD_BUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 530, -1, -1));

        btnD_MOSTRAR.setBackground(new java.awt.Color(153, 153, 153));
        btnD_MOSTRAR.setForeground(new java.awt.Color(51, 51, 51));
        btnD_MOSTRAR.setText("Mostrar");
        btnD_MOSTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD_MOSTRARActionPerformed(evt);
            }
        });
        jPanel1.add(btnD_MOSTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, -1, -1));

        btnD_AGREGAR.setBackground(new java.awt.Color(153, 153, 153));
        btnD_AGREGAR.setForeground(new java.awt.Color(51, 51, 51));
        btnD_AGREGAR.setText("Agregar");
        btnD_AGREGAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD_AGREGARActionPerformed(evt);
            }
        });
        jPanel1.add(btnD_AGREGAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 530, -1, -1));

        btnD_MODIFICAR.setBackground(new java.awt.Color(153, 153, 153));
        btnD_MODIFICAR.setForeground(new java.awt.Color(51, 51, 51));
        btnD_MODIFICAR.setText("Modificar");
        btnD_MODIFICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD_MODIFICARActionPerformed(evt);
            }
        });
        jPanel1.add(btnD_MODIFICAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, -1, -1));

        btnD_ELIMINAR.setBackground(new java.awt.Color(153, 153, 153));
        btnD_ELIMINAR.setForeground(new java.awt.Color(51, 51, 51));
        btnD_ELIMINAR.setText("Eliminar");
        btnD_ELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD_ELIMINARActionPerformed(evt);
            }
        });
        jPanel1.add(btnD_ELIMINAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 530, -1, -1));

        btnD_LIMPIAR.setBackground(new java.awt.Color(153, 153, 153));
        btnD_LIMPIAR.setForeground(new java.awt.Color(51, 51, 51));
        btnD_LIMPIAR.setText("Limpiar");
        btnD_LIMPIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD_LIMPIARActionPerformed(evt);
            }
        });
        jPanel1.add(btnD_LIMPIAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 530, -1, -1));

        btnD_ACTUALIZAR1.setBackground(new java.awt.Color(153, 153, 153));
        btnD_ACTUALIZAR1.setForeground(new java.awt.Color(51, 51, 51));
        btnD_ACTUALIZAR1.setText("Actualizar");
        btnD_ACTUALIZAR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD_ACTUALIZAR1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnD_ACTUALIZAR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 530, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnD_MOSTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD_MOSTRARActionPerformed
     MostrarDireccion();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnD_MOSTRARActionPerformed

    private void btnD_AGREGARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD_AGREGARActionPerformed
    if(!"".equals(txtD_ID.getText())|| !"".equals(txtD_ALCALDIA.getText()) ||!"".equals(txtD_CP.getText()) ||!"".equals(txtD_CALLE.getText()) ||!"".equals(txtD_NUM_EXT.getText()) ||!"".equals(txtD_COLONIA.getText()) ||!"".equals(txtD_ID_ESTADO.getText()))
    {
        Direccion direccion = new Direccion();
        
        direccion.setID_DIRECCION(txtD_ID.getText());
        direccion.setALCALDIA_MUNICIPIO(txtD_ALCALDIA.getText());
        direccion.setCP(txtD_CP.getText());
        direccion.setCALLE(txtD_CALLE.getText());
        direccion.setNUM_EXT(txtD_NUM_EXT.getText());
        direccion.setCOLONIA(txtD_COLONIA.getText());
        direccion.setID_ESTADO(txtD_ID_ESTADO.getText());
        
        DireccionDAO direccionDAO = new DireccionDAO();
        direccionDAO.AgregarDireccion(direccion);
        
        JOptionPane.showMessageDialog(null, "Direccion Registrado");
    }
    else
    {
        JOptionPane.showMessageDialog(null, "Campos Vacios");
    }
    
    LimpiarTable();
    MostrarDireccion();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnD_AGREGARActionPerformed

    private void btnD_MODIFICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD_MODIFICARActionPerformed
    if("".equals(txtD_ID.getText()))
    {
        JOptionPane.showMessageDialog(null, "Seleccione una Fila");
    }
    else
    {
        if(!"".equals(txtD_ID.getText())|| "".equals(txtD_ALCALDIA.getText()) ||"".equals(txtD_CP.getText()) ||"".equals(txtD_CALLE.getText()) ||"".equals(txtD_NUM_EXT.getText()) ||"".equals(txtD_COLONIA.getText()) ||"".equals(txtD_ID_ESTADO.getText()))
        
        {
            dir.setID_DIRECCION(txtD_ID.getText());
            dir.setALCALDIA_MUNICIPIO(txtD_ALCALDIA.getText());
            dir.setCP(txtD_CP.getText());
            dir.setCALLE(txtD_CALLE.getText());
            dir.setNUM_EXT(txtD_NUM_EXT.getText());
            dir.setCOLONIA(txtD_COLONIA.getText());
            dir.setID_ESTADO(txtD_ID_ESTADO.getText());
            
            dirdao.ModificarDireccion(dir);
            JOptionPane.showMessageDialog(null, "Direccion Modificada");
        }
    }
    LimpiarTable();
    MostrarDireccion();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnD_MODIFICARActionPerformed

    private void btnD_ELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD_ELIMINARActionPerformed
    if(!"".equals(txtD_ID.getText()))
    {
        int pregunta = JOptionPane.showConfirmDialog(null, "¡Desea Eliminar?");
        if (pregunta == 0)
        {
            String ID_DIRECCION = (txtD_ID.getText());
            dirdao.EliminarDireccion(ID_DIRECCION); //720 Ltable, prod lostprot
        }
    }
    LimpiarTable();
    MostrarDireccion();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnD_ELIMINARActionPerformed

    private void btnD_LIMPIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD_LIMPIARActionPerformed
    LimpiarTable();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnD_LIMPIARActionPerformed

    private void btnD_BUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD_BUSCARActionPerformed
        String idDireccion = txtD_ID.getText();
        String alcaldiaMunicipio = txtD_ALCALDIA.getText();
        String cP = txtD_CP.getText();
        String calle = txtD_CALLE.getText();
        String numExt = txtD_NUM_EXT.getText();
        String colonia = txtD_COLONIA.getText();
        String idEstado = txtD_ID_ESTADO.getText();
        
        List<Direccion> BusquedaDir = dirdao.BuscarDireccion(idDireccion, alcaldiaMunicipio, cP, calle, numExt, colonia, idEstado);
        
        LimpiarTable();
        
        for(Direccion dir : BusquedaDir)
        {
            Object[] filad = {dir.getID_DIRECCION(), dir.getALCALDIA_MUNICIPIO(), dir.getCP(), dir.getCALLE(), dir.getNUM_EXT(), dir.getCOLONIA(), dir.getID_ESTADO()};
            modelo.addRow(filad);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnD_BUSCARActionPerformed

    private void btnD_ACTUALIZAR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD_ACTUALIZAR1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnD_ACTUALIZAR1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Direccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Direccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Direccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Direccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Direccion2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnD_ACTUALIZAR1;
    private javax.swing.JButton btnD_AGREGAR;
    private javax.swing.JButton btnD_BUSCAR;
    private javax.swing.JButton btnD_ELIMINAR;
    private javax.swing.JButton btnD_LIMPIAR;
    private javax.swing.JButton btnD_MODIFICAR;
    private javax.swing.JButton btnD_MOSTRAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbDireccion;
    private javax.swing.JTextField txtD_ALCALDIA;
    private javax.swing.JTextField txtD_CALLE;
    private javax.swing.JTextField txtD_COLONIA;
    private javax.swing.JTextField txtD_CP;
    private javax.swing.JTextField txtD_ID;
    private javax.swing.JTextField txtD_ID_ESTADO;
    private javax.swing.JTextField txtD_NUM_EXT;
    // End of variables declaration//GEN-END:variables
}
